agent:
  step_limit: 60

environment:
  environment_class: docker

model:
  cost_tracking: "ignore_errors"
  model_name: "openai/meta/muse-glimmer-30b"
  model_kwargs:
    api_base: "http://127.0.0.1:8080/v1"
    api_key: "proxy"
    temperature: 1.0
    top_p: 0.95
    drop_params: true
    parallel_tool_calls: true
    extra_body:
      top_k: 64
